import { ConvexClientProvider } from "./providers/convex-client-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
